unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# Split windows
bind -n C-t split-window -h
bind -n C-y split-window -v
bind -n C-w kill-pane

# Navigate panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Disable visual notifications
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

# Enable mouse
set -g mouse on

# Use zsh as default shell
set-option -g default-shell /bin/zsh
